<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BD_TRAMPO</RootNamespace>
    <UserSecretsId>cb43acd1-400f-4f6e-ae41-014919b961db</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Usuario.cs" />
    <Compile Remove="Tests/**/*.cs" />
    <Content Remove="Tests/**;artifacts/**;docs/**;Scripts/**;.github/**" />
    <None Remove="Tests/**" />
    <Content Update="appsettings.Development.json" CopyToPublishDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

</Project>
